# Generated by Django 5.2.5 on 2025-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
