# Generated by Django 5.2.5 on 2025-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_location_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendido')], default='available', max_length=10),
        ),
    ]
